### ISSUE TITLE
[Question] How to find patterns in string columns?

### ISSUE THREAD

**Issue by kanekotic** [DeNederlandscheBank/data-patterns#1]
* data-patterns version: 0.1.18
* Python version: 3.7
* Operating System: OSX

### Description

Seems the library finds pattern in columns that are numeric. Is it able to find patterns also in string columns?

**Comment by wjwillemse** [comment]
Yes, the library is able to derive patterns from strings. For example, with the dataset in the documentation, we can run the expression 'IF ({"Type"} = [.*non.*@]) THEN({.*} > 0)'. This looks for rules where in the column Type contains the string "non" (it uses a regex) and then derives patterns where the value of another column is higher than zero. This works in a IF-statement, it does not seems to work without one.

**Comment by kanekotic** [comment]
@wjwillemse thanks for your response. 

I think i did not expressed myself I was thinking more on the usage of the pattern operator. As I wanted to to find unknown  patterns in pairs of related columns.

I Manage to use the library by grouping the data-frame and later encode the string values to respective integer values. so '=' patterns could be found.

Nevertheless maybe a recommendation to evolve the library would be that patterns should not apply to numerical fields only but also to any other matching type fields.  so if you are trying to find fuzzy patterns.

I would like to add my congrats on developing a great library. It is very useful and can bring a lot of value.

**Comment by wjwillemse** [comment]
Reopened the issue, because I'd like to understand you suggestion and perhaps we can work out an improvement of the package based on your suggestion. 

Do you mean that you would like additional pattern operators such as 'in', that would check if the left hand side is a substring of the right hand side? If not, could you give an example?

The package stores the patterns that are found into Pandas code (boolean masks), so if a pattern can in principle be expressed as a Pandas code then we could look for a way to include it in the expression with which the package is run.

**Comment by kanekotic** [comment]
sure. I will create an example notebook, so you can understand what i commented.
